/* Access codes use the same server session and library as email sign-in. */
(()=>{
 const settings=document.getElementById('phonePreferences');if(!settings)return;
 const account=document.createElement('section');account.id='accessAccount';
 account.innerHTML=`<h3>Account</h3><p id="accessAccountStatus">Checking account...</p><button type="button" class="small-btn" id="accessEmailSignIn">Sign in with email</button><form id="accessActivateForm"><label for="accessCodeInput">Access Code</label><input id="accessCodeInput" type="password" autocomplete="off" placeholder="Paste your access code" required maxlength="80"><button class="save-btn" type="submit">ACTIVATE</button><p role="status"></p></form><section id="accessAdmin" hidden><h3>Admin · Access Codes</h3><p>One code per user. Anyone with the code can use that account. Copy it now; it cannot be displayed again.</p><form id="accessCreateForm"><label for="accessLabel">User label</label><input id="accessLabel" maxlength="100" required><label for="accessDays">Valid for (days)</label><input id="accessDays" type="number" min="1" max="365" value="7" required><button class="small-btn" type="submit">CREATE CODE</button></form><div id="accessCreated" hidden><input aria-label="New access code" readonly><button type="button" class="small-btn">COPY CODE</button></div><p id="accessAdminStatus" role="status"></p><div id="accessCodeList"></div></section>`;
 settings.querySelector('h2').after(account);
 const $=id=>document.getElementById(id);
 async function request(url,method='GET',body){const r=await fetch(url,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed.');return data;}
 async function refresh(){
  try{const {user}=await request('/api/auth/me');$('accessAccountStatus').textContent=user.isAdmin?'Signed in · Admin':'Signed in';$('accessAccountStatus').classList.add('account-signed-in');$('accessEmailSignIn').hidden=true;$('accessActivateForm').hidden=true;$('accessAdmin').hidden=!user.isAdmin;if(user.isAdmin)try{await list();}catch(e){$('accessAdminStatus').textContent=e.message;}}
  catch{$('accessAccountStatus').textContent='Not signed in';$('accessAccountStatus').classList.remove('account-signed-in');$('accessEmailSignIn').hidden=false;$('accessActivateForm').hidden=false;$('accessAdmin').hidden=true;$('accessCreated').hidden=true;$('accessCreated').querySelector('input').value='';}
 }
 $('accessEmailSignIn').onclick=()=>{settings.close();showAuth('Sign in with your email.',()=>{void refresh();window.dispatchEvent(new Event('focus'));});};
 function activation(form,input){form.addEventListener('submit',async e=>{
  e.preventDefault();const button=form.querySelector('button'),status=form.querySelector('[role=status]');button.disabled=true;status.textContent='Activating...';
  try{const {user}=await request('/api/auth/access-code','POST',{code:input.value});input.value='';await showAuthenticated(user);const action=pendingAuthAction;pendingAuthAction=null;if(typeof action==='function')await action(user);status.textContent='Activated.';settings.close();window.dispatchEvent(new Event('focus'));await refresh();}
  catch(error){status.textContent=error.message;}finally{button.disabled=false;}
 });}
 activation($('accessActivateForm'),$('accessCodeInput'));
 // Also offer the same option from AI Listen's existing SIGN IN entry point.
 const alternate=document.createElement('form');alternate.innerHTML='<label for="authAccessCode">Or use an Access Code</label><input id="authAccessCode" type="password" autocomplete="off" required maxlength="80" placeholder="Paste your access code"><button type="submit" class="save-btn">ACTIVATE</button><p role="status"></p>';
 $('authCancelBtn').before(alternate);activation(alternate,$('authAccessCode'));
 async function list(){const {codes}=await request('/api/admin/access-codes');$('accessCodeList').replaceChildren();for(const item of codes){const row=document.createElement('div'),text=document.createElement('p'),button=document.createElement('button');text.textContent=item.label+' · '+(item.disabled?'Disabled':Number(item.expires_at)<=Date.now()?'Expired':'Active')+' · '+new Date(Number(item.expires_at)).toLocaleString();button.textContent='DISABLE';button.className='small-btn';button.disabled=!!item.disabled;button.onclick=async()=>{if(!confirm('Disable this access code? Its sessions will lose access.'))return;button.disabled=true;try{await request('/api/admin/access-codes','DELETE',{id:item.id});await list();}catch(e){$('accessAdminStatus').textContent=e.message;button.disabled=false;}};row.append(text,button);$('accessCodeList').append(row);}}
 $('accessCreateForm').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;try{const data=await request('/api/admin/access-codes','POST',{label:$('accessLabel').value,days:Number($('accessDays').value)});$('accessCreated').hidden=false;$('accessCreated').querySelector('input').value=data.code;$('accessAdminStatus').textContent='Created. Copy and give this code only to its user.';await list();}catch(e){$('accessAdminStatus').textContent=e.message;}finally{button.disabled=false;}};
 $('accessCreated').querySelector('button').onclick=async()=>{try{await navigator.clipboard.writeText($('accessCreated').querySelector('input').value);$('accessAdminStatus').textContent='Copied.';}catch{$('accessCreated').querySelector('input').select();$('accessAdminStatus').textContent='Select and copy the code manually.';}};
 new MutationObserver(()=>{if(settings.open)void refresh();else{$('accessCreated').hidden=true;$('accessCreated').querySelector('input').value='';}}).observe(settings,{attributes:true,attributeFilter:['open']});
})();
