/* Customer plans and admin-issued top-ups share the existing account/library. */
(()=>{
 const settings=document.getElementById('phonePreferences');if(!settings)return;
 const $=id=>document.getElementById(id),money=n=>'₱'+Number(n).toFixed(2);
 let knownUser=null,busy=false;
 const account=document.createElement('section');account.id='accessAccount';
 account.innerHTML=`<h3>Credits</h3><p id="accessAccountStatus">Activate Free access or redeem a Pro code.</p><p id="creditBalance"></p><p id="freeBalance"></p><button type="button" class="small-btn" id="activateFree">USE FREE ACCESS</button><form id="accessActivateForm"><label for="accessCodeInput">Enter / Redeem Code</label><input id="accessCodeInput" type="password" autocomplete="off" placeholder="Paste your code" required maxlength="80"><button class="save-btn" type="submit">REDEEM</button><p role="status"></p></form><button type="button" class="small-btn" id="requestTopup" hidden>REQUEST TOP-UP</button><p id="topupStatus" role="status"></p><details id="adminEntry"><summary>Admin sign-in</summary><button type="button" class="small-btn" id="accessEmailSignIn">Sign in with email</button></details><section id="accessAdmin" hidden><h3>Admin · Credits</h3><p>Confirm payment before creating a code. 60% becomes customer usage credits; 40% is your share before expenses. Credits have no expiry.</p><form id="accessCreateForm"><label for="accessLabel">User label</label><input id="accessLabel" maxlength="100" required><label for="accessPayment">Payment received (₱)</label><input id="accessPayment" type="number" min="400" max="100000" step="1" value="400" required><label for="accessTarget">Existing customer ID (optional for first activation)</label><input id="accessTarget" inputmode="numeric"><button class="small-btn" type="submit">CREATE CODE</button></form><div id="accessCreated" hidden><input aria-label="New credit code" readonly><button type="button" class="small-btn">COPY CODE</button></div><p id="accessAdminStatus" role="status"></p><form id="billingRateForm"><label for="billingRate">Billing rate: PHP per US$1</label><input id="billingRate" type="number" min="1" max="1000" step="0.01" value="65" required><button type="submit" class="small-btn">SAVE RATE</button></form><h4>Top-up requests</h4><div id="topupList"></div><h4>Customer balances</h4><div id="creditCustomerList"></div><h4>Issued codes</h4><div id="accessCodeList"></div></section>`;
 settings.querySelector('h2').after(account);
 async function request(url,method='GET',body){const r=await fetch(url,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed.');return data;}
 function credits(data){$('creditBalance').textContent='Pro credits: '+money(data.balance);$('freeBalance').textContent='Free: '+data.freeRemaining+' / 1,000 characters left this week · Resets '+new Date(data.resetAt).toLocaleDateString();}
 async function refresh(){
  if(busy)return;busy=true;
  try{const {user}=await request('/api/auth/me');knownUser=user;document.body.dataset.accountRole=user.isAdmin?'admin':'customer';$('accessAccountStatus').textContent=user.isAdmin?'Signed in · Admin':'Access active · Customer '+user.id;$('accessAccountStatus').classList.add('account-signed-in');$('activateFree').hidden=true;$('adminEntry').hidden=true;$('requestTopup').hidden=!!user.isAdmin;$('accessAdmin').hidden=!user.isAdmin;credits(await request('/api/credits'));if(user.isAdmin)await list();}
  catch{$('accessAdmin').hidden=true;if(!knownUser){document.body.dataset.accountRole='guest';$('accessAccountStatus').textContent='Activate Free access or redeem a Pro code.';$('activateFree').hidden=false;$('adminEntry').hidden=false;}}
  finally{busy=false;}
 }
 async function enter(user){await showAuthenticated(user);knownUser=user;const action=pendingAuthAction;pendingAuthAction=null;if(typeof action==='function')await action(user);settings.close();window.dispatchEvent(new Event('focus'));void refresh();}
 async function free(button,status){button.disabled=true;try{await enter((await request('/api/auth/free','POST',{})).user);}catch(e){status.textContent=e.message;}finally{button.disabled=false;}}
 $('activateFree').onclick=()=>free($('activateFree'),$('topupStatus'));
 $('accessEmailSignIn').onclick=()=>{settings.close();showAuth('Admin email sign-in',()=>{knownUser=null;void refresh();window.dispatchEvent(new Event('focus'));});$('authEmailOptions').open=true;};
 function activation(form,input){form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button'),status=form.querySelector('[role=status]');button.disabled=true;try{await enter((await request('/api/auth/access-code','POST',{code:input.value})).user);input.value='';status.textContent='Code accepted.';}catch(e){status.textContent=e.message;}finally{button.disabled=false;}});}
 activation($('accessActivateForm'),$('accessCodeInput'));
 const alternate=document.createElement('form');alternate.innerHTML='<label for="authAccessCode">Access / Top-up Code</label><input id="authAccessCode" type="password" autocomplete="off" required maxlength="80" placeholder="Paste your code"><button type="submit" class="save-btn">REDEEM</button><p role="status"></p>';
 $('authCancelBtn').before(alternate);activation(alternate,$('authAccessCode'));
 const freeButton=document.createElement('button');freeButton.type='button';freeButton.className='small-btn';freeButton.textContent='USE FREE ACCESS';freeButton.onclick=()=>free(freeButton,alternate.querySelector('[role=status]'));alternate.after(freeButton);
 const emailOptions=document.createElement('details');emailOptions.id='authEmailOptions';emailOptions.innerHTML='<summary>Admin / existing email sign-in</summary>';
 const emailLabel=document.querySelector('label[for="authEmail"]'),emailRow=$('authEmail').parentElement;
 emailLabel.before(emailOptions);emailOptions.append(emailLabel,emailRow,$('authCodeStep'),$('authStatus'));
 $('requestTopup').onclick=async()=>{const b=$('requestTopup');b.disabled=true;try{await request('/api/topup-request','POST',{});$('topupStatus').textContent='Top-up request sent to the owner. Wait for payment instructions and your code.';}catch(e){$('topupStatus').textContent=e.message;}finally{b.disabled=false;}};
 async function list(){const data=await request('/api/admin/access-codes');$('billingRate').value=data.usdPhp;for(const id of ['topupList','creditCustomerList','accessCodeList'])$(id).replaceChildren();
  for(const item of data.requests){const row=document.createElement('p');row.textContent=item.label+' · Customer '+item.user_id+' · '+item.status+' · '+new Date(Number(item.requested_at)).toLocaleString();if(item.status==='pending'){const b=document.createElement('button');b.className='small-btn';b.textContent='PREPARE TOP-UP';b.onclick=()=>{$('accessLabel').value=item.label;$('accessTarget').value=item.user_id;$('accessPayment').focus();};row.append(b);}$('topupList').append(row);}
  for(const item of data.accounts){const p=document.createElement('p');p.textContent=item.label+' · Customer '+item.user_id+' · '+money(Number(item.balance)/1e6);$('creditCustomerList').append(p);}
  for(const item of data.codes){const p=document.createElement('p');p.textContent=item.label+' · Paid '+money(Number(item.paid)/1e6)+' · Credits '+money(Number(item.credit)/1e6)+' · '+(item.redeemed_user?'Redeemed by '+item.redeemed_user:'Not redeemed');$('accessCodeList').append(p);}
 }
 $('accessCreateForm').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;try{const data=await request('/api/admin/access-codes','POST',{label:$('accessLabel').value,pesos:Number($('accessPayment').value),userId:$('accessTarget').value.trim()||null});$('accessCreated').hidden=false;$('accessCreated').querySelector('input').value=data.code;$('accessAdminStatus').textContent='Created '+money(data.credit)+' credits. Copy this private code now; it is shown only once.';await list();}catch(e){$('accessAdminStatus').textContent=e.message;}finally{button.disabled=false;}};
 $('accessCreated').querySelector('button').onclick=async()=>{try{await navigator.clipboard.writeText($('accessCreated').querySelector('input').value);$('accessAdminStatus').textContent='Copied.';}catch{$('accessCreated').querySelector('input').select();$('accessAdminStatus').textContent='Select and copy the code manually.';}};
 $('billingRateForm').onsubmit=async e=>{e.preventDefault();try{await request('/api/admin/access-codes','PATCH',{usdPhp:Number($('billingRate').value)});$('accessAdminStatus').textContent='Billing rate saved for new sessions.';}catch(e){$('accessAdminStatus').textContent=e.message;}};
 new MutationObserver(()=>{if(settings.open)void refresh();else{$('accessCreated').hidden=true;$('accessCreated').querySelector('input').value='';}}).observe(settings,{attributes:true,attributeFilter:['open']});
 // Desktop Audio is an admin surface; the server separately protects /api/session.
 for(const id of ['listenAudioBtn','audioStart'])$(id)?.addEventListener('click',e=>{
  if(matchMedia('(max-width:600px), (max-width:1200px) and (max-height:600px) and (hover:none) and (pointer:coarse)').matches||knownUser?.isAdmin)return;
  e.preventDefault();e.stopImmediatePropagation();showAuth('Desktop Audio is available to the administrator only.',()=>{knownUser=null;void refresh();});emailOptions.open=true;
 },true);
 window.addEventListener('focus',()=>{knownUser=null;void refresh();});window.addEventListener('mb-credits',e=>credits(e.detail));void refresh();
})();
